package com.cmcc.test;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.http.HttpResponse;
import org.apache.http.util.EntityUtils;
import org.testng.Assert;
import org.testng.annotations.Test;

import com.asserts.AssertResult;
import com.asserts.Asserts;
import com.data.provider.testng.ExcelDataProvider;
import com.protocol.httpclient.HttpClientImpl;

/**
 * This code is generated by FreeMarker
 * @author Lenovo
 * @date 2017-4-18 9:07:11
 * Description: test class description
 */
public class GetEnterpriseTest{

	private static Log LOGGER = LogFactory.getLog(GetEnterpriseTest.class);

    /********** test method ***********/
    @Test(dataProvider="defaultMethod", dataProviderClass=ExcelDataProvider.class)
    public void testGetEnterprise(String caseId, String caseDesc, String method, String url, String reqHeader, String reqParams, String statusCode, String reasonPhrase, String rspHeader, String rspBody) {
    	LOGGER.info("########## " + caseId + ": " + caseDesc + " ##########"+" BEGIN ##########");
		try {
			HttpClientImpl client = new HttpClientImpl(url, reqHeader, reqParams);
			HttpResponse rsp = client.doRequest(method);
			
			Assert.assertEquals(String.valueOf(rsp.getStatusLine().getStatusCode()), statusCode);
			Assert.assertEquals(rsp.getStatusLine().getReasonPhrase(), reasonPhrase);
			if(null != rspHeader && rspHeader.trim().length() > 0){
				AssertResult result = Asserts.assertJson(client.convertHeards2Json(rsp.getAllHeaders()), RspHeader);
				Assert.assertTrue(result.isSucc(), result.getMessage());
			}
			if(null != rspBody && rspBody.trim().length() > 0){
				AssertResult result = Asserts.assertJson(EntityUtils.toString(rsp.getEntity()), rspBody);
				Assert.assertTrue(result.isSucc(), result.getMessage());
			}
		} catch(Exception e) {
			Assert.fail(e.toString());
		}finally{
			LOGGER.info("########## " + caseId + ": " + caseDesc + " ##########"+" END ##########");
		}		
    }

}
